### ISSUE TITLE
CI is failing on main since Nov/Dec 2022

### ISSUE THREAD

**Issue by kytrinyx** [exercism/purescript#262]
CI has been failing for quite some time, and I have no experience with purescript.

@aimorris @emiel would either of you have a moment to see if there's an easy fix here?

There are quite a few open PRs that we probably should pull in, if we can get CI passing.

/cc @ErikSchierboom for visibility

**Comment by emiel** [comment]
Hi all. 

I did a little debugging and found the root cause. We are still using PureScript 0.14.x (0.15.x is the latest). There was an issue with 0.14.7 having an incorrect dependency on `libtinfo` (see https://github.com/purescript/purescript/issues/4253).

If you invoke `purs --version` on CI you'll see:

```
purs: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

To resolve we can bump PureScript to 0.14.9 which appears to work. We usually bump the PureScript in tandem with purescript-runner. Another option is upgrade to the latest (0.15.x) but that requires much more work because the exercises need to be adapted as well.

I can create a couple of PRs for this if needed. Let me know.

**Comment by emiel** [comment]
See:
* https://github.com/exercism/purescript-test-runner/pull/44
* https://github.com/exercism/purescript/pull/263

**Comment by kytrinyx** [comment]
That was quick! Thank you so much.

Yeah, I think bumping purescript to 0.14.9 is the way to go here. If someone wants to take on the bigger task of bumping up to the next minor version, that's great, but it doesn't need to happen right this second.

I've reopened the PR that bumps the patch version, and will merge it as soon as CI reports back (it reruns CI when the PR is reopened, it looks like).
